[package]
name = "fst-file"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-primitive-derive = "0.2.2"
nom = "7.1.3"
num = "0.4.0"
num-traits = "0.2.15"
thiserror = "1.0.40"
