[package]
name = "wave_go_brrrrr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
fst-file = {path = "fst-file"}

[workspace]
members = ["fst-file"]
